# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test on Main

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -e .
        pip3 install black isort flake8 pytest
    - name: Code lint
      run: |
        black moe_peft
        isort moe_peft --profile black
        flake8 moe_peft --show-source --statistics --max-line-length=128 --max-complexity 15 --ignore=E203,W503,E722
    - name: Run tests
      run: |
        pytest
